[build]
  publish = "/"
  command = "# no build command needed"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' https://app.radiocult.fm https://fonts.googleapis.com https://fonts.gstatic.com https://kit.fontawesome.com https://cdnjs.cloudflare.com https://picsum.photos https://embed.radio.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; script-src 'self' 'unsafe-inline' https://kit.fontawesome.com https://cdnjs.cloudflare.com https://embed.radio.co; img-src 'self' data: https://picsum.photos https://gensparkpublicblob.blob.core.windows.net; media-src 'self' https://app.radiocult.fm https://embed.radio.co; connect-src 'self' https://embed.radio.co;"
