[build]
  publish = "/"
  command = "# no build command needed"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' https://app.radiocult.fm https://api.radiocult.fm https://fonts.googleapis.com https://fonts.gstatic.com https://kit.fontawesome.com https://cdnjs.cloudflare.com https://picsum.photos; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; script-src 'self' 'unsafe-inline' https://kit.fontawesome.com https://cdnjs.cloudflare.com; img-src 'self' data: https://picsum.photos https://api.radiocult.fm; media-src 'self' https://app.radiocult.fm; connect-src 'self' https://api.radiocult.fm;"
